version: '3'
services:
  downloader:
    restart: always
    build: .
    ports:
      - 8080:8080
    volumes:
      - /mnt/md0/shared/anime:/mnt/md0/shared/anime
      - /mnt/md0/shared/videos:/mnt/md0/shared/videos
      - /mnt/md0/shared/music:/mnt/md0/shared/music
